services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password

  dev_postgres:
    image: postgres:18.0-alpine3.22
    container_name: project_dev_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_dev_db
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test_postgres:
    image: postgres:18.0-alpine3.22
    container_name: project_test_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project_test_db
    ports:
      - "5443:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_test_data:
